Section11
awunderground/data-science-for-public-policy2 pull request #28
Opened 2023-12-29 16:09 UTC by awunderground

2024-01-15 17:24 UTC, Deckart2 requested changes
Hey @awunderground I have looked through and left some comments on chapters 11 - 13. A few bigger picture things to note:

1. Level of detail is inconsistent: For much of this book, you are quite detailed. I think some of the content here is also, but some sections are not. Specifically, I thought all of chapter 12 could use more fleshing out (and I tried to be helpful there). I also feel like I could have used more details for MARS. 
2. I would revisit your references. Something here looked off. 
3. You add a note earlier, but in Chapter 13, I think you should make reference to the Interpretable Machine Learning book again. When you reference interpretable models, you are talking about interpretability in only one sense. That book discusses other ways to interpret seemingly black-box models (for example, Shapley values, LIME)
4. For chapter 13, I really liked how each model built on the last one. I also liked the chapter 11 and chapter 13 final comparisons 


Let me know if these comments are clear! Happy to follow up as needed.

2024-01-15 17:24 UTC, Deckart2 commented on 13_interpretable-models.qmd
> +[^13_interpretable-models-1]: The [Council of Economic Advisers "cubic model" of Covid-19 cases](https://www.vox.com/2020/5/8/21250641/kevin-hassett-cubic-model-smoothing) is one high profile example
Excellent reference. This article is insane

2024-01-15 17:24 UTC, Deckart2 commented on 13_interpretable-models.qmd
> +autoplot(enet_tuning)
Can you add some commentary on these charts. I am not sure what is happening

2024-01-15 17:24 UTC, Deckart2 commented on 13_interpretable-models.qmd
> +Regularization doesn't help much in this case. This makes sense because the regression specification is parsimonious and deliberate.
Good commentary

2024-01-15 17:24 UTC, Deckart2 commented on 13_interpretable-models.qmd
> +Finally, let's compare the RMSE and $r$-squared for linear regression and MARS (with hyperparameter tuning).
Again, could we use `gt()` here please?

2024-01-15 17:24 UTC, Deckart2 requested changes
Hey @awunderground I have looked through and left some comments on chapters 11 - 13. A few bigger picture things to note:

1. Level of detail is inconsistent: For much of this book, you are quite detailed. I think some of the content here is also, but some sections are not. Specifically, I thought all of chapter 12 could use more fleshing out (and I tried to be helpful there). I also feel like I could have used more details for MARS. 
2. I would revisit your references. Something here looked off. 
3. You add a note earlier, but in Chapter 13, I think you should make reference to the Interpretable Machine Learning book again. When you reference interpretable models, you are talking about interpretability in only one sense. That book discusses other ways to interpret seemingly black-box models (for example, Shapley values, LIME)
4. For chapter 13, I really liked how each model built on the last one. I also liked the chapter 11 and chapter 13 final comparisons 


Let me know if these comments are clear! Happy to follow up as needed.

2024-02-19 01:33 UTC, awunderground commented on 11_ensembling.qmd
> +## Planning Database
Great note

2024-02-19 01:33 UTC, awunderground commented on 11_ensembling.qmd
> +-   **Motivation:** The decennial census is used to allocate hundreds of billions of dollars and to redistrict political power. Ensuring an accurate count is imperative. The Census Bureau uses the pl
Added

2024-02-19 01:34 UTC, awunderground commented on 11_ensembling.qmd
> +This exercise began with the Hard to Count Score [@bruce2001; @bruce2003]. The authors used theory to develop an index of twelve variables correlated with non response and under counting to sort cens
Changed

2024-02-19 01:34 UTC, awunderground commented on 11_ensembling.qmd
> +This is clearly a predictive task but the authors brought a traditional social sciences approach.
Changed

2024-02-19 01:34 UTC, awunderground commented on 11_ensembling.qmd
> +In 2012, the US Census Bureau crowd sourced a predictive modeling competition on Kaggle [@erdman2014; @erdman2017]. The competition was motivated by the America COMPETES act. [Kaggle competitions](ht
Changed

2024-02-19 01:36 UTC, awunderground commented on 11_ensembling.qmd
> +Participants use the 2012 Block-Group-Level Planning Database and were evaluated using mean squared error weighted by 2010 population.[^11_ensembling-1]
It's unclear! But I changed the footnote.

2024-02-19 01:36 UTC, awunderground commented on 11_ensembling.qmd
> +244 teams and individuals competed. Bill Bame, a software develop from Maryland, won the competition with a mean squared error of 2.60. The top three finished use ensembled tree-based models like ran
Good call!

2024-02-19 02:03 UTC, awunderground commented on 11_ensembling.qmd
> +  add_role(State_name, County_name, Low_Response_Score, new_role = "id") |>
`Low_Response_Score` is the model predicted outcome variable. `non_response_rate` is the variable we are trying to model to create a low response score. 

Adding `Low_Response_Score` as an "id" variables means it won't be included as a predictor.

2024-02-19 02:04 UTC, awunderground commented on 11_ensembling.qmd
> +  add_role(State_name, County_name, Low_Response_Score, new_role = "id") |>
I added a clarifying sentence!

2024-02-19 02:05 UTC, awunderground commented on 11_ensembling.qmd
> +lm_resamples |>
I will beef this up when I add the ML material from DSPP1.

2024-02-19 02:05 UTC, awunderground commented on 11_ensembling.qmd
> +The mean is typically used to ensemble in regression applications and majority vote is typically use to ensemble in classification applications.
Done.

2024-02-19 02:06 UTC, awunderground commented on 11_ensembling.qmd
> +## Random Forests Algorithm
Changed!

2024-02-19 02:07 UTC, awunderground commented on 11_ensembling.qmd
> +Regularization is a change to a loss function or algorithm intended to intentionally reduce the intensity of a model fit to reduce variance error.
What do you mean by complexity? Ridge regression only changes the magnitude of coefficients and doesn't select features.

2024-02-19 02:08 UTC, awunderground commented on 11_ensembling.qmd
> +Random forests are regularized models, and have similarities to linear regression with ridge regression, even though it is a non-parametric model.
Nice edit.

2024-02-19 02:08 UTC, awunderground commented on 11_ensembling.qmd
> +Linear regression is easy to interpret because the fitting process is simple and linear regression models have a finite number of clear regression coefficients. Regression trees result in a clear tre
Changed!

2024-02-19 02:09 UTC, awunderground commented on 11_ensembling.qmd
> +Linear regression is easy to interpret because the fitting process is simple and linear regression models have a finite number of clear regression coefficients. Regression trees result in a clear tre
Added.

2024-02-19 02:10 UTC, awunderground commented on 11_ensembling.qmd
> +Variable importance is an alternative approach that aims to capture the why of a model and prediction. For linear regression, variable importance is typically just the absolute value of the estimated
Good note

2024-02-19 02:15 UTC, awunderground commented on 11_ensembling.qmd
> +For regression with random forests, variable importance is the reduction in mean squared error caused by the addition of each predictor across all of the trees. It can be imprecise for categorical pr
Added

2024-02-19 02:17 UTC, awunderground commented on 11_ensembling.qmd
> +For regression with random forests, variable importance is the reduction in mean squared error caused by the addition of each predictor across all of the trees. It can be imprecise for categorical pr
I feel like I get to your later point a little bit later in these notes!

2024-02-19 02:21 UTC, awunderground commented on 11_ensembling.qmd
> +Coordinating the parallelization requires extra computation but concurrently running the task on multiple cores can often save time.
Added!

2024-02-19 02:22 UTC, awunderground commented on 11_ensembling.qmd
> +We will focus on two forms of parallelization. First, parallelization is simple with bagged models because trees are independently grow. Simply include `num.threads` in the `set_engine()` call.
Great catch

2024-02-19 02:24 UTC, awunderground commented on 11_ensembling.qmd
> +Parallelization is more difficult with boosted models, which are sequentially trained. The hyperparameter tuning later in this chapter uses a more complex socket parallelization with the following se
Added!

2024-02-19 02:28 UTC, awunderground commented on 11_ensembling.qmd
> +1.  Set $\hat{f}(\vec{x}) = 0$ and $r_i = y_i$ where $r_i$ is the $i^{th}$ residual and $y_i$ is the observed value for the $i^{th}$ observation in the training data.
The difference is the explicit mention of trees

2024-02-19 02:29 UTC, awunderground commented on 12_regularization.qmd
> +  # vi() |>
Removed!

2024-02-19 02:29 UTC, awunderground commented on 12_regularization.qmd
> +Let's fit a linear regression model on the PDB data set.
Nice addition.

2024-02-19 02:30 UTC, awunderground commented on 12_regularization.qmd
> +## Ridge Regression
Changed!

2024-02-19 02:31 UTC, awunderground commented on 12_regularization.qmd
> +### Elastic net blends Ridge regression and LASSO regression
Deleted for now.

2024-02-19 02:36 UTC, awunderground commented on 13_interpretable-models.qmd
> +Like in earlier sections, we will use the simulated example 1 data to demonstrate some model fits.
I need to come up with a different name for the data. It's from DSPP1. I will clean this up when I fold in that content!

2024-02-19 02:36 UTC, awunderground commented on 13_interpretable-models.qmd
> +Polynomial regression is still linear regression because the model is linear in its coefficients but can fit non-linear patterns in the data
Thank you

2024-02-19 02:37 UTC, awunderground commented on 13_interpretable-models.qmd
> +@fig-simulated-regression shows four different linear regression models fit to the training data. Degree is the magnitude of the highest order term included in the model.
I _think_ I fixed this in a different update.

2024-02-19 02:42 UTC, awunderground commented on 13_interpretable-models.qmd
> +Interactions extend polynomials to consider multiplying predictors by other predictors in addition to multiplying them by themselves. Including pairwise or triplewise interactions complicates interpr
Done.

2024-02-19 02:43 UTC, awunderground commented on 13_interpretable-models.qmd
> +Simple pairwise interactions for the small planning database example explodes the number of predictors from 23 to 276.
Added

2024-02-19 03:06 UTC, Deckart2 commented on 11_ensembling.qmd
> +Regularization is a change to a loss function or algorithm intended to intentionally reduce the intensity of a model fit to reduce variance error.
Fair point! Nonetheless, I still don't know what "intensity" means.

2024-02-19 03:10 UTC, awunderground commented on 13_interpretable-models.qmd
> +Step functions break the range of a predictor into bins and then fit different constant (intercept only models) in each bin. @fig-piecewise-constant-regression shows piecewise constant regression fit
Changed

2024-02-19 03:11 UTC, awunderground commented on 13_interpretable-models.qmd
> +Regression splines have a degree, which determines the order of the polynomials (e.g. 1 is linear and and 3 is cubic). Regression splines also have knots, which are the break points between regions.
I'm going to keep it because the first half of the sentence is very important.

2024-02-19 03:11 UTC, awunderground commented on 13_interpretable-models.qmd
> +@fig-developing-splines shows several piecewise polynomial regression models fit to the simulated example 1 data. The first panel shows a piecewise linear model. Note the discontinuity. The second pa
I think this will get worked out!

2024-02-19 03:14 UTC, awunderground commented on 13_interpretable-models.qmd
> +This leaves picking the number and location of the knots. The location of knots is typically evenly spaced out (e.g. three knots will be placed at the 25th, 50th, and 75th percentiles). The number of
These are different:

1. Hyperparameter tuning controls the number of evenly spaced knots to include. All knots are included. 
2. Regularization drops specific knots using penalization. In this case, 10 evenly spaced knots may be included in the model without regularization but the regularization drops the 2nd, 4th, and 8th knots.

2024-03-23 12:14 UTC, awunderground commented on 11_ensembling.qmd
> +pdb_small <- read_csv(here::here("data", "pdb_small.csv"))
it should now be on the branch.

2024-03-23 12:20 UTC, awunderground commented on 11_ensembling.qmd
> +In practice, the number of trees does not need to be tuned and using too many trees will not lead to a model that is overfit. Typically, the number of trees can be set in the 100 to 500 range based o
I switched to the word generally. The stack overflow post is interesting but describes edge cases. 

RF are much more sensitive to changes in min_n and mtry.

2024-03-23 12:39 UTC, awunderground commented on 11_ensembling.qmd
> +rf_final |>
Added

2024-12-27 16:33 UTC, closed without merging