Stage reorg
awunderground/data-science-for-public-policy2 pull request #34
Opened 2024-02-25 22:08 UTC by Deckart2

Hi @awunderground! 

I have made the structure updates to the yaml and other files based on the guidance in [issue 30](https://github.com/awunderground/data-science-for-public-policy2/issues/30) as best I could. I do have a few questions for you (and may have to change some numbers if my assumptions are wrong):

1. Do we want to include the reading list file from the original repo? I assume no
2. Do we want to include the EDA quarto document? I assumed yes
3. Is the plan to combine the course 1 simulation and sampling and course 2 simulation and sampling material? I am assuming so
4. Do we want to include the cloud computing section material from course 1? I am assuming so
5. Will a new R package section be developed (presumably out of the start of the `functions.qmd` file in this repo? I am assuming so.

2024-02-25 23:44 UTC, awunderground commented
1. In the long run, yes! For now, no.
2. Yes!
3. No. They are closely related.
4. Not for now.
5. Yes!

2024-02-26 01:52 UTC, Deckart2 commented
Awesome! I think this section should be ready to go then.

2024-03-13 10:49 UTC, awunderground requested changes
This is great!

I sent you the necessary files to add the remaining chapters from the 2nd class on Slack. The chapters may take a long time to render the first time you render the full document. I set up caching, so hopefully this is a rare challenge.

2024-03-13 11:46 UTC, awunderground commented on 19_predictive-modeling-review.qmd
The images and references are broken for this section.

2024-03-18 03:16 UTC, Deckart2 commented on 19_predictive-modeling-review.qmd
It looks ok over here. Am I mi
![Screen Shot 2024-03-17 at 11 16 12 PM](https://github.com/awunderground/data-science-for-public-policy2/assets/49692322/968
![Screen Shot 2024-03-17 at 11 16 03 PM](https://github.com/awunderground/data-science-for-public-policy2/assets/49692322/7a522baf-22db-4604-85a7-bc44bb901f24)
d2ee4-3e1e-431f-8f04-ac89f2fb0fdd)
ssing something

2024-08-27 11:12 UTC, merged